const ItemData = [
    { name: "Carrot", weightDivisor: 0.275, baseValue: 20, growthTime: 100 },
    { name: "Strawberry", weightDivisor: 0.3, baseValue: 15, growthTime: 100 },
    { name: "Blueberry", weightDivisor: 0.2, baseValue: 20, growthTime: 100 },
    { name: "Orange Tulip", weightDivisor: 0.05, baseValue: 850, growthTime: 55 },
    { name: "Tomato", weightDivisor: 0.5, baseValue: 30, growthTime: 100 },
    { name: "Corn", weightDivisor: 2, baseValue: 40, growthTime: 100 },
    { name: "Daffodil", weightDivisor: 0.2, baseValue: 1000, growthTime: 45 },
    { name: "Watermelon", weightDivisor: 7, baseValue: 3000, growthTime: 70 },
    { name: "Pumpkin", weightDivisor: 8, baseValue: 3400, growthTime: 80 },
    { name: "Apple", weightDivisor: 3, baseValue: 275, growthTime: 50 },
    { name: "Bamboo", weightDivisor: 4, baseValue: 4000, growthTime: 35 },
    { name: "Coconut", weightDivisor: 14, baseValue: 400, growthTime: 70 },
    { name: "Cactus", weightDivisor: 7, baseValue: 3400, growthTime: 100 },
    { name: "Dragon Fruit", weightDivisor: 12, baseValue: 4750, growthTime: 100 },
    { name: "Mango", weightDivisor: 15, baseValue: 6500, growthTime: 200 },
    { name: "Grape", weightDivisor: 3, baseValue: 7850, growthTime: 200 },
    { name: "Mushroom", weightDivisor: 25, baseValue: 151000, growthTime: 220 },
    { name: "Pepper", weightDivisor: 5, baseValue: 8000, growthTime: 200 },
    { name: "Cacao", weightDivisor: 8, baseValue: 12000, growthTime: 250 },
    { name: "Beanstalk", weightDivisor: 10, baseValue: 28000, growthTime: 300 },
    { name: "Ember Lily", weightDivisor: 12, baseValue: 55555, growthTime: 450 },
    { name: "Sugar Apple", weightDivisor: 9, baseValue: 48000, growthTime: 200 },
    { name: "Chocolate Carrot", weightDivisor: 0.275, baseValue: 11000, growthTime: 100 },
    { name: "Red Lollipop", weightDivisor: 4, baseValue: 50000, growthTime: 65 },
    { name: "Blue Lollipop", weightDivisor: 1, baseValue: 50000, growthTime: 65 },
    { name: "Candy Sunflower", weightDivisor: 1.5, baseValue: 80000, growthTime: 85 },
    { name: "Easter Egg", weightDivisor: 3, baseValue: 2500, growthTime: 20 },
    { name: "Candy Blossom", weightDivisor: 3, baseValue: 100000, growthTime: 40 },
    { name: "Peach", weightDivisor: 2, baseValue: 300, growthTime: 70 },
    { name: "Raspberry", weightDivisor: 0.75, baseValue: 100, growthTime: 70 },
    { name: "Pineapple", weightDivisor: 3, baseValue: 2000, growthTime: 70 },
    { name: "Papaya", weightDivisor: 3, baseValue: 1000, growthTime: 60 },
    { name: "Banana", weightDivisor: 1.5, baseValue: 1750, growthTime: 100 },
    { name: "Passionfruit", weightDivisor: 3, baseValue: 3550, growthTime: 40 },
    { name: "Soul Fruit", weightDivisor: 25, baseValue: 7750, growthTime: 200 },
    { name: "Cursed Fruit", weightDivisor: 30, baseValue: 25750, growthTime: 200 },
    { name: "Mega Mushroom", weightDivisor: 70, baseValue: 500, growthTime: 2000000 },
    { name: "Cherry Blossom", weightDivisor: 3, baseValue: 500, growthTime: 400 },
    { name: "Purple Cabbage", weightDivisor: 5, baseValue: 500, growthTime: 70 },
    { name: "Lemon", weightDivisor: 1, baseValue: 350, growthTime: 50 },
    { name: "Pear", weightDivisor: 3, baseValue: 500, growthTime: 20 },
    { name: "Pink Tulip", weightDivisor: 0.05, baseValue: 850, growthTime: 55 },
    { name: "Avocado", weightDivisor: 2, baseValue: 500, growthTime: 150 },
    { name: "Cranberry", weightDivisor: 1, baseValue: 3000, growthTime: 50 },
    { name: "Durian", weightDivisor: 8, baseValue: 7000, growthTime: 200 },
    { name: "Eggplant", weightDivisor: 5, baseValue: 9500, growthTime: 220 },
    { name: "Lotus", weightDivisor: 20, baseValue: 25000, growthTime: 650 },
    { name: "Venus Fly Trap", weightDivisor: 10, baseValue: 45000, growthTime: 650 },
    { name: "Nightshade", weightDivisor: 0.5, baseValue: 3500, growthTime: 100 },
    { name: "Glowshroom", weightDivisor: 0.75, baseValue: 300, growthTime: 100 },
    { name: "Mint", weightDivisor: 1, baseValue: 5250, growthTime: 150 },
    { name: "Moonflower", weightDivisor: 2, baseValue: 9500, growthTime: 200 },
    { name: "Starfruit", weightDivisor: 3, baseValue: 15000, growthTime: 250 },
    { name: "Moonglow", weightDivisor: 7, baseValue: 25000, growthTime: 400 },
    { name: "Moon Blossom", weightDivisor: 3, baseValue: 66666, growthTime: 400 },
    { name: "Crimson Vine", weightDivisor: 1, baseValue: 1250, growthTime: 100 },
    { name: "Moon Melon", weightDivisor: 8, baseValue: 18000, growthTime: 300 },
    { name: "Blood Banana", weightDivisor: 1.5, baseValue: 6000, growthTime: 200 },
    { name: "Celestiberry", weightDivisor: 2, baseValue: 10000, growthTime: 200 },
    { name: "Moon Mango", weightDivisor: 15, baseValue: 50000, growthTime: 300 },
    { name: "Rose", weightDivisor: 1, baseValue: 5000, growthTime: 100 },
    { name: "Foxglove", weightDivisor: 2, baseValue: 20000, growthTime: 250 },
    { name: "Lilac", weightDivisor: 3, baseValue: 35000, growthTime: 250 },
    { name: "Pink Lily", weightDivisor: 6, baseValue: 65000, growthTime: 400 },
    { name: "Purple Dahlia", weightDivisor: 12, baseValue: 75000, growthTime: 400 },
    { name: "Sunflower", weightDivisor: 16.5, baseValue: 160000, growthTime: 600 },
    { name: "Lavender", weightDivisor: 0.275, baseValue: 25000, growthTime: 90 },
    { name: "Nectarshade", weightDivisor: 0.8, baseValue: 50000, growthTime: 100 },
    { name: "Nectarine", weightDivisor: 3, baseValue: 48000, growthTime: 200 },
    { name: "Hive Fruit", weightDivisor: 8, baseValue: 62000, growthTime: 300 },
    { name: "Manuka Flower", weightDivisor: 0.3, baseValue: 25000, growthTime: 200 },
    { name: "Dandelion", weightDivisor: 4, baseValue: 50000, growthTime: 300 },
    { name: "Lumira", weightDivisor: 6, baseValue: 85000, growthTime: 350 },
    { name: "Honeysuckle", weightDivisor: 12, baseValue: 100000, growthTime: 400 },
    { name: "Crocus", weightDivisor: 0.275, baseValue: 30000, growthTime: 150 },
    { name: "Succulent", weightDivisor: 5, baseValue: 25000, growthTime: 175 },
    { name: "Violet Corn", weightDivisor: 3, baseValue: 50000, growthTime: 250 },
    { name: "Bendboo", weightDivisor: 18, baseValue: 155000, growthTime: 275 },
    { name: "Cocovine", weightDivisor: 14, baseValue: 66666, growthTime: 275 },
    { name: "Dragon Pepper", weightDivisor: 6, baseValue: 88888, growthTime: 300 },
    { name: "Bee Balm", weightDivisor: 1, baseValue: 18000, growthTime: 200 },
    { name: "Nectar Thorn", weightDivisor: 7, baseValue: 44444, growthTime: 350 },
    { name: "Suncoil", weightDivisor: 10, baseValue: 80000, growthTime: 400 },
    { name: "Noble Flower", weightDivisor: 5, baseValue: 20000, growthTime: 250 },
    { name: "Elephant Ears", weightDivisor: 15, baseValue: 20000, growthTime: 250 },
    { name: "Traveler's Fruit", weightDivisor: 2, baseValue: 20000, growthTime: 250 },
    { name: "Parasol Flower", weightDivisor: 2, baseValue: 25000, growthTime: 50 },
    { name: "Prickly Pear", weightDivisor: 3, baseValue: 5000, growthTime: 300 },
    { name: "Green Apple", weightDivisor: 3, baseValue: 3500, growthTime: 200 },
    { name: "Loquat", weightDivisor: 3, baseValue: 5000, growthTime: 200 },
    { name: "Ice Cream Bean", weightDivisor: 4, baseValue: 4500, growthTime: 200 },
];

  
const Rarity = [
    ["Normal", 1000, 1],
    ["Gold", 10, 20],
    ["Rainbow", 1, 50]
];
  
const Mutations = {
    "Meteoric" : { "ValueMulti" : 125 },
    "Pollinated" : { "ValueMulti" : 3 },
    "Celestial" : { "ValueMulti" : 120 },
    "Moonlit" : { "ValueMulti" : 2 },
    "Windstruck" : { "ValueMulti" : 5 },
    "Burnt" : { "ValueMulti" : 4 },
    "Shocked" : { "ValueMulti" : 100 },
    "Disco" : { "ValueMulti" : 125 },
    "Twisted" : { "ValueMulti" : 5 },
    "Wet" : { "ValueMulti" : 2 },
    "Choc" : { "ValueMulti" : 2 },
    "Molten" : { "ValueMulti" : 25 },
    "Dawnbound" : { "ValueMulti" : 150 },
    "Cooked" : { "ValueMulti" : 10 },
    "Chilled" : { "ValueMulti" : 2 },
    "Heavenly" : { "ValueMulti" : 5 },
    "Bloodlit" : { "ValueMulti" : 4 },
    "Voidtouched" : { "ValueMulti" : 135 },
    "Plasma" : { "ValueMulti" : 5 },
    "Zombified" : { "ValueMulti" : 25 },
    "HoneyGlazed" : { "ValueMulti" : 5 },
    "Frozen" : { "ValueMulti" : 10 }
};

  
module.exports = {
    ItemData,
    Rarity,
    Mutations
};
  
